config/routes.rb
Authbot::Application.routes.draw do

  resources :authentications 
  match '/auth/:provider/callback', :to => "authentications#create"
  match 'logout', to: 'authentications#destroy', as: "destroy_authentication"

  root :to => 'authorizations#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :uid

  def self.find_or_create_by_auth(auth)
    return nil unless passes_whitelist?(auth)
    user = User.find_by_uid(auth["uid"])
    unless user 
      user = User.create(:first_name => auth["info"]["first_name"], 
                         :last_name => auth["info"]["last_name"],
                         :email => auth["info"]["email"], 
                         :uid => auth["uid"])
    end 
    user
  end 

  def self.passes_whitelist?(auth)
    if auth["info"]["email"].split("@").last.upcase == "HUNGRYMACHINE.COM"
      true
    else 
      false
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user 
    if cookies["uid"]
      user = User.find_by_uid(cookies["uid"])
    end 
    user
  end 

  helper_method :current_user


end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    # This will never get hit; this is merely a placeholder for
    # a root_path whose responsibility is to redirect to the main app.
  end

  def create
    @omniauth = request.env["omniauth.auth"]
    @user = User.find_or_create_by_auth(@omniauth) if @omniauth
    set_cookie(@user) if @user
    return redirect_to root_url(port: 80, only_path: false)
  end 

  def destroy
    cookies.delete("uid")
    cookies.delete("user_name")
    return redirect_to root_url(port: 80, only_path: false)
  end

  def set_cookie(user)
    cookies["uid"] = user.uid
    cookies["user_name"] = user.first_name + " " + user.last_name
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/create.html.erb
    <%= current_user.inspect %> <br /><hr> 
    <%= cookies.inspect %> <br /><hr> 
    <%= @user.inspect %> <br /><hr> 
    <%= link_to "Destroy Login", destroy_authentication_path, :method => :delete %>
    <%= link_to "Exit debut mode", "http://localhost:3001/" %>

app/views/authentications/destroy.html.erb
<%= cookies.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authbot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>